name: CI/CD Pipeline - Recipe Sharing App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install backend dependencies
        working-directory: backend
        run: npm install
      - name: Run backend tests
        working-directory: backend
        run: npm test

      # Frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install
      - name: Run frontend tests
        working-directory: frontend
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Backend to Cloud Run
        run: gcloud builds submit --config cloudbuild-backend.yaml

      - name: Deploy Frontend to Cloud Run
        run: gcloud builds submit --config cloudbuild-frontend.yaml
